version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    expose:
    - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    expose:
    - 3306
    ports:
    - "3306:3306"